# Generated by Django 5.2 on 2025-04-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProduit', models.CharField(max_length=200)),
                ('prixUnitaire', models.FloatField()),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
